# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-SQLEngine
version:      0.91
version_from: SQLEngine.pm
installdirs:  site
requires:
    Class::MakeMethods:            1.006
    DBI:                           1
    DBIx::AnyDBD:                  2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
