=head1 NAME

DBIx::SQLEngine::ToDo - Tasks, ideas, and bugs

=head1 TO DO

Although it based on earlier code that was extensively tested over several years of production use, this code has recently been majorly refactored, and has not yet been sufficiently tested in its new form.


=head2 Internals

Review, perhaps switch to use of new DBI subclassing functionality in place of DBIx::AnyDBD.


=head2 Distribution

The test script is fairly minimal and really ought to exercise the entire public interface.

For comapbility with the CPAN installer and automated testing tools, it may be more appropriate to query for a test DSN in the Makefile.PL, rather than in the test.pl.


=head2 Columns

The column-information retrieve in DBIx::SQLEngine::Default should be using DBI's type_info methods.


=head2 Interface

Extend the base interface with the following interfaces:

=over 4

=item *

fetch_select_with_limit

=item *

do_insert_with_sequence

=back


=head2 Transactions

There's no transaction support at this point; at least a basic version should be added.


=head2 Criteria

The Criteria subclasses are woefully incomplete.

=head2 Subclasses

Additional subclass logic will be required to support the following:

=over 4

=item *

All: type of long field

=item *

Oracle: single, trailing long.

=item *

MySQL, Oracle: downcase column names.

=item *

DB2: Long insertion via multiple updates.

=item *

Informix: escape newlines on insert/update/where and select

=back

=cut

=head1 SEE ALSO 

L<DBIx::SQLEngine::ReadMe>

=cut
